name: Deploy Nginx Proxy 🚀

on:
  pull_request:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        run: sh docker/deploy.sh

      - name: 🚀 Update Website
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: sh update-proxy.sh

      - name: 🔀 Merge Pull Request
        uses: BaharaJr/merge-pr@0.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
